### ISSUE TITLE
Not working as expected on Android Chrome

### ISSUE THREAD

**Issue by gregorholzmann** [jsonberry/goScrollYourself#1]
Scroll direction detection seems buggy on Android Chrome -- since the "scrollUp" method is fired on default this logic in `determineDirection isn't working as expected:

```
if (e.deltaY > 0 || window.scrollY > goScrollYourself.scrollYCache) {
        direction = 'onDown'
    } else {
        direction = 'onUp'
    }
```

I'll see if I can get a PR up to fix this.

**Comment by jsonberry** [comment]
Fixed with #2
